version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  configserver:
    environment:
      CONFIG_SERVICE_PASSWORD: CONFIG_SERVICE_PASSWORD
    image: config
    build: config
    restart: always
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health || exit 1"]
      interval: 30s
      timeout: 30s

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: CONFIG_SERVICE_PASSWORD
    image: registry
    build: registry
    restart: always
    depends_on:
      - configserver
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

#  mongodb:
#    image: mongo
#    build: mongodb
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: user
#      MONGO_INITDB_ROOT_PASSWORD: MONGODB_PASSWORD
#      MONGO_INITDB_DATABASE: springCloud
#    ports:
#      - 27017:27017
#    volumes:
#      - /data/db:/data/db
#
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: user
#      ME_CONFIG_MONGODB_ADMINPASSWORD: MONGODB_PASSWORD

  mongo:
    image: mongodb
    build: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example