version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - './data/rabbitmq:/var/lib/rabbitmq'

  configserver:
    environment:
      CONFIG_SERVICE_PASSWORD: CONFIG_SERVICE_PASSWORD
    image: config
    build: config
    restart: always
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: CONFIG_SERVICE_PASSWORD
    image: registry
    build: registry
    restart: always
    depends_on:
      - configserver
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  mongodb:
    image: mongodb
    build: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: springCloud
    volumes:
      - './data/db:/data/db'
      - './data/configdb:/data/configdb'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongodb:mongo
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: MONGODB_PASSWORD

#  auth-service:
#    environment:
#      CONFIG_SERVICE_PASSWORD: CONFIG_SERVICE_PASSWORD
#      NOTIFICATION_SERVICE_PASSWORD: NOTIFICATION_SERVICE_PASSWORD
#      STATISTICS_SERVICE_PASSWORD: STATISTICS_SERVICE_PASSWORD
#      ACCOUNT_SERVICE_PASSWORD: ACCOUNT_SERVICE_PASSWORD
#      MONGODB_PASSWORD: MONGODB_PASSWORD
#    image: auth-service
#    build: auth-service
#    restart: always
#    ports:
#      - 5000:5000
#    depends_on:
#      - configserver
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "10"

